#ifndef OPENTABLELOADFACTORS_HPP
#define OPENTABLELOADFACTORS_HPP

#define LH_MIN_SIZE_LOG_2 8

#define LH_MIN_LOAD_FACTOR .15L
#define LH_MAX_LOAD_FACTOR .5L


//#define EXP_TRUE(EXPRESSION) __builtin_expect(EXPRESSION, true)
//#define EXP_FALSE(EXPRESSION) __builtin_expect(EXPRESSION, false)


#define EXP_TRUE(EXPRESSION) EXPRESSION
#define EXP_FALSE(EXPRESSION) EXPRESSION

#define DYNAMIC_GROW

#endif //OPENTABLELOADFACTORS_HPP
